#ifndef __SHADERS__
#pragma once
#endif


#define MAIN_DESC_SET_GLOBALS 0
#define MAIN_DESC_SET_INSTANCES 1
#define MAIN_DESC_SET_MATERIALS 2
#define MAIN_DESC_SET_TEXTURES 3
#define MAIN_DESC_SET_SAMPLER 4
#define MAIN_DESC_SET_NOISE 5
#define MAIN_DESC_SET_STORAGE_IMAGE 6





#define MAIN_BINDING_GLOBAL_GLOBAL 0
#define MAIN_BINDING_GLOBAL_CAMERA 1
#define MAIN_BINDING_GLOBAL_LIGHT 2
